apiVersion: v1
kind: Service
metadata:
  name: auto-suggest
  labels:
    run: auto-suggest
spec:
  type: LoadBalancer
  selector:
    run: auto-suggest
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  externalIPs:
  - 10.0.0.100        